Team-Capple/Capple-Server

- src/main/java/com/server/capple/domain/answer/entity/AnswerHeart.java
- src/main/java/com/server/capple/domain/question/entity/QuestionHeart.java
- src/main/java/com/server/capple/domain/tag/Tag.java
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[x] 의존성, 환경 변수, 빌드 관련 코드 업데이트
fix/#10/heart-redis-setting -> develop
questionHeart, answerHeart를 레디스 DB에 저장하도록 엔티티를 수정하였습니다.
> [FIX] QuestionHeart, AnswerHeart Redis로 저장하도록 수정

- src/main/java/com/server/capple/domain/question/entity/Question.java
- src/main/java/com/server/capple/domain/question/entity/QuestionStatus.java
feature/#14/StatusEntity -> develop
- QuestionStatus enum 클래스 생성
- Question 엔티티 status 필드 추가
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
> [FEAT] Question엔티티 Status 필드 추가 및 Status Enum Class 추가

- src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
- src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java
- src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
- src/main/java/com/server/capple/domain/answer/repository/AnswerHeartRedisRepository.java
- src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
- src/main/java/com/server/capple/domain/answer/service/AnswerService.java
- src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
- src/main/java/com/server/capple/domain/member/controller/MemberController.java
- src/main/java/com/server/capple/domain/member/dto/MemberResponse.java
- src/main/java/com/server/capple/domain/member/repository/MemberRepository.java
- src/main/java/com/server/capple/domain/member/service/MemberService.java
- src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
- src/main/java/com/server/capple/global/utils/S3ImageComponent.java
- #26
feature/#26/delete-orphanage-images -> develop
1. 프로필 이미지에 사용되지 않는 이미지를 S3 버킷에서 삭제하는 기능을 추가했습니다.
> [FEAT] S3 고아 이미지 삭제 기능 추가

- src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
- src/main/java/com/server/capple/domain/question/entity/Question.java
- src/main/java/com/server/capple/domain/question/repository/AdminQuestionRepository.java
- src/main/java/com/server/capple/domain/question/scheduler/QuestionScheduler.java
- src/main/java/com/server/capple/domain/question/service/AdminQuestionService.java
- src/main/java/com/server/capple/domain/question/service/AdminQuestionServiceImpl.java
- src/main/java/com/server/capple/domain/tag/controller/TagController.java
- src/main/java/com/server/capple/domain/tag/repository/TagRedisRepository.java
- src/main/java/com/server/capple/domain/tag/scheduler/TagScheduler.java
- src/main/java/com/server/capple/domain/tag/service/TagService.java
- src/main/java/com/server/capple/domain/tag/service/TagServiceImpl.java
- src/main/java/com/server/capple/global/exception/errorCode/QuestionErrorCode.java
- src/main/java/com/server/capple/global/exception/errorCode/TagErrorCode.java
- src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java
- src/test/java/com/server/capple/domain/question/service/QuestionServiceTest.java
- src/test/java/com/server/capple/domain/tag/service/TagServiceTest.java
- src/test/java/com/server/capple/support/ServiceTestConfig.java
ex) feature/#43/popular keyword -> develop
1. 인기 키워드 조회 API를 추가하였습니다. (현재 사용될 축소화된 서비스에서는 사용되지 않는 기능입니다.)
2. 스케줄러를 통해 QuestionStatus를 변경시켜 LIVE 질문을 올리고, 닫도록 하였습니다.
- 매일 오전 7시에, 오후 6시에 LIVE 질문 올리기
- 매일 오전 1시에, 오후 14시에 LIVE 질문 내리기
질문 올리기와 내리기 서비스 test결과입니다.
스케줄러를 사용하기 때문에 로그를 통해 스케줄러 실행 확인이 가능하도록 하였습니다.
> [FEAT] 인기키워드 조회 API, Question Status 변경 Schedular 작성

- src/main/java/com/server/capple/domain/member/controller/MemberController.java
- src/main/java/com/server/capple/domain/member/dto/MemberResponse.java
- src/main/java/com/server/capple/domain/member/entity/Member.java
- src/main/java/com/server/capple/domain/member/mapper/MemberMapper.java
- src/main/java/com/server/capple/domain/member/repository/MemberRepository.java
- src/main/java/com/server/capple/domain/member/service/MemberService.java
- src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
feature/#47/DeleteMember -> develop
- 회원 탈퇴 API 구현
- 회원 탈퇴시 해당 사용자가 삭제됨으로 인한 답변이 불러와지지 않는 오류 해결 및 알 수 없음으로 닉네임 변경 기능 구현
> [FEAT] 회원 탈퇴 API 구현

- src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
- src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
fix/#58/FixGetQuestionListAPI -> develop
- 질문 상태(OLD, LIVE)에 따른 질문 모아보기 조회 API 수정
- - 질문 상태(OLD, LIVE)에 따른 메인질문 조회 API 수정
> [FIX] 질문 모아보기 상태에 따른 리턴값 수정

- src/main/java/com/server/capple/config/security/SecurityConfig.java
- src/main/java/com/server/capple/config/security/auth/CustomUserDetails.java
- src/main/java/com/server/capple/config/security/jwt/service/JwtService.java
- src/main/java/com/server/capple/config/security/jwt/service/JwtServiceImpl.java
- src/main/java/com/server/capple/domain/member/controller/MemberController.java
- src/main/java/com/server/capple/domain/member/entity/Member.java
- src/main/java/com/server/capple/domain/member/entity/Role.java
- src/main/java/com/server/capple/domain/member/repository/MemberRepository.java
- src/main/java/com/server/capple/domain/member/service/MemberService.java
- src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
feature/#46/security-refactor -> develop
- 회원가입 시 이메일 중복체크
- 이메일 암호화 메서드
- jwt의 암호화 키값에 이메일을 섞어 claim 상에서 email을 발견할 수 없도록 하였습니다.
- 암호화는 가능하지만 복호화는 어려움
- 이메일이 같은 값을 경우 jwt 값이 같으므로 중복 체크 또한 가능
- 닉네임 중복체크
- 인가에 대한 구현
- `/admin` 로 시작하는 엔드포인트는 ADMIN role을 가진 사용자만 사용할 수 있습니다.
- 로그인, 회원가입, 토큰 재생성, 닉네임 중복체크, 이메일 중복 체크는 토큰 없이 접근 가능하도록 하였습니다.
- Role 변경 API
- ADMIN 과 ACADEMIER 두개로 나눴습니다.
- 테스트 코드 작성 없이 수행으로 검증하였습니다. 추후 테스트 코드 작성할 예정입니다.
> [REFACTOR] 회원가입, 인가 관련 기능 리팩터링

- src/main/java/com/server/capple/domain/question/repository/AdminQuestionRepository.java
- src/main/java/com/server/capple/domain/question/service/AdminQuestionServiceImpl.java
ex) feature#43/polular-keyword-> develop
live질문 open 시 question id가 빠른 것부터 live로 설정
> fix: #43 id가 가장 빠른 Question을 return하도록 수정

- src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
feature/#71/encrypt-email -> develop
- 기존의 이메일 암호화 메서드를 회원가입, 이메일 체크 로직에 적용
- 이메일아 jwt 형식으로 잘 저장됨을 확인하였습니다.
- 이메일 중복체크 로직도 잘 동작됨을 확인하였습니다.
> [FEAT]: #71 이메일 암호화 적용

- src/main/java/com/server/capple/domain/mail/vo/MailDomain.java
chore/#79/mail-domain-change -> develop
- 인증 메일 도메인을 `pos.idserve.net`로 변경하였습니다.
> [CHORE] 메일 인증 지원 도메인 변경

- src/main/java/com/server/capple/config/security/oauth/apple/client/AppleAuthClient.java
- src/main/java/com/server/capple/config/security/oauth/apple/service/AppleAuthServiceImpl.java
- src/main/java/com/server/capple/domain/member/controller/MemberController.java
- src/main/java/com/server/capple/global/exception/errorCode/AppleOauthError.java
feat/#83/apple-login-error-handling -> develop
- 로그인 실패 시 반환 에러 재정의
- 로그인 반환 에러 스웨거 적용
> [FEAT] 로그인 시 클라이언트 에러 핸들링 및 반환 데이터 정의

- src/main/java/com/server/capple/config/security/SecurityConfig.java
- src/main/java/com/server/capple/domain/mail/repository/MailWhitelistRedisRepository.java
- src/main/java/com/server/capple/domain/mail/service/MailService.java
- src/main/java/com/server/capple/domain/mail/service/MailServiceImpl.java
- src/main/java/com/server/capple/domain/member/controller/MemberController.java
- src/main/java/com/server/capple/domain/member/service/MemberService.java
- src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
feat/#90/emailVerificationWhitelist -> develop
- 레디스를 이용하여 이메일 인증 시 도메인 검증을 거치지 않는 화이트 리스트를 구현하였습니다.
- 만료시간을 이용하여 화이트 리스트의 데이터가 삭제되도록 하였습니다.
- 화이트 리스트 생성 API는 관리자 권한을 가진 액세스 토큰을 이용해서만 사용 가능합니다.
화이트 리스트 생성 (권한 없는 토큰)
화이트 리스트 생성 (관리자 권한 토큰)
> Feat: #90 이메일 인증 화이트 리스트 기능 구현

- src/main/java/com/server/capple/domain/mail/service/MailService.java
- src/main/java/com/server/capple/domain/mail/service/MailServiceImpl.java
- src/main/java/com/server/capple/domain/mail/service/MailUtil.java
- src/main/java/com/server/capple/domain/mail/service/MailUtilImpl.java
- src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
refactor/#92/certCodeGenerate -> develop
- 화이트리스트 고정 인증코드 방식 변경
- 고정암호는 환경변수로 관리
- 화이트리스트 저장시 이메일 암호화 변경
- 기존의 화이트리스트의 이메일이 노출되는 키값 방식에서 다음과 같이 암호화되도록 변경하였습니다.
> [REFACTOR] 화이트리스트 고정 인증코드 방식 변경 및 화이트리스트 저장시 이메일 암호화 변경

- src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
- src/main/java/com/server/capple/domain/question/dao/QuestionInfoInterface.java
- src/main/java/com/server/capple/domain/question/entity/Question.java
- src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
- src/main/java/com/server/capple/domain/question/scheduler/QuestionScheduler.java
- src/main/java/com/server/capple/domain/question/service/AdminQuestionService.java
- src/main/java/com/server/capple/domain/question/service/AdminQuestionServiceImpl.java
- src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
- src/main/java/com/server/capple/domain/tag/controller/TagController.java
- src/main/java/com/server/capple/domain/tag/repository/TagRedisRepository.java
- src/main/java/com/server/capple/domain/tag/service/TagService.java
- src/main/java/com/server/capple/domain/tag/service/TagServiceImpl.java
- src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java
- src/test/java/com/server/capple/domain/question/service/QuestionServiceTest.java
- src/test/java/com/server/capple/domain/tag/controller/TagControllerTest.java
- src/test/java/com/server/capple/domain/tag/service/TagServiceTest.java
- src/test/java/com/server/capple/support/ControllerTestConfig.java
- src/test/java/com/server/capple/support/ServiceTestConfig.java
ex) fix/#99/FixQuestionTagSave -> develop
스케줄러로 인해 LIVE 질문이 닫히면 RDB Question 테이블 tags column에 인기 태그 3개 저장
애초에 question zset이 만들어질 때 expired 기한을 7시간으로 하여 생성 (라이브 닫히면 자동으로 사라짐)
질문 목록 조회 시
OLD 질문 -> RDB Question tags에서 태그 반환
LIVE 질문 -> 레디스 question-tag zset에서 인기 태그 3개 반환
tags 필드는 String으로 '태그1 태그2 태그3'과 같이 저장합니다. (수정될 일 X)
zset 만료는 로그로 확인하였습니다!
> [FIX] 질문 Tag 저장 방식 변경

- .github/workflows/ci.yml
- .github/workflows/cicd-production.yml
- .github/workflows/cicd-release.yml
- .gitignore
- Dockerfile-deploy
- build.gradle
- docker-compose.local.yml
- docker-compose.prod.yml
- docker-compose.release.yml
- docker-compose.test.yml
- src/main/java/com/server/capple/config/SwaggerConfig.java
- src/test/java/com/server/capple/CappleApplicationTests.java
- src/test/java/com/server/capple/domain/answer/controller/AnswerControllerTest.java
- src/test/java/com/server/capple/domain/member/controller/MemberControllerTest.java
- src/test/java/com/server/capple/domain/tag/controller/TagControllerTest.java
- src/test/java/com/server/capple/support/ControllerTestConfig.java
- src/test/java/com/server/capple/support/ServiceTestConfig.java
feature/#100/productionDeploy -> develop
- Github flow 에서 Git Flow로 브랜치 전략 변경
- 운영과 테스트, 개발이 함께 진행되기 위한 브랜치 전략으로 Github flow가 적합하지 않다고 판단하여 Git Flow로 브랜치 전략을 변경 하였습니다.
- 브랜치를 다섯가지로 나누어 운영할 예정입니다.
- master
- 운영서버이며, 직접적인 커밋을 수행하지 않고 merge 커밋을 생성하고 커밋에 tag를 하여 배포됩니다.
- tag는 `v{버전}`으로 명명 되며 버전은 x.x.x와 같은 형식으로 정의됩니다. 각각 (큰 기능의 추가 구현 횟수).(릴리즈로부터의 추가 횟수).(hotfix로 인한 추가 횟수) 의 형식으로 버전을 나눕니다.
- hotfix
- 운영서버에서 발생한 오류를 수정하기위한 브랜치입니다.
- 브랜치명은 `hotfix/{기능 이름}`으로 명명됩니다.
- `master` 브랜치에서 분기되어 `master`와 `develop`브랜치로 병합됩니다.
- release
- QA를 위한 브랜치입니다.
- 기능상의 추가 구현을 제외한 에러를 잡기위한 커밋만 수행됩니다.
- 브랜치명은 `release-{버전}`으로 명명 됩니다.
- 버전은 `master` 브랜치에 다음으로 등록될 버전으로 정의합니다.
- `develop`브랜치에서 분기되어 `master` 브랜치로 병합됩니다. (추가적인 수정사항이 존재할 경우 `develop` 브랜치로도 병합)
- develop
- 기존의 `develop` 와 같은 방식으로 추가 기능 개발이 이루어지는 브랜치입니다.
- …
> [CHORE] #100 릴리즈 서버 분리 및 브랜치 전략 변경

- src/main/java/com/server/capple/config/SchedulerConfig.java
hotfix/schedulerErrorHandler -> master
- 스케줄러에서 발생하던 에러가 핸들링 되지 않고 있던 오류를 수정하였습니다.
- 스케줄러의 Configuration 파일을 생성하였습니다.
- 스케줄러의 스레드 개수를 1개로 정의하였습니다.
- 질문의 상태 변화에서만 사용하고 있기 때문에 다수의 스레드를 사용할 필요가 없다고 생각했습니다.
- 스케줄러 에러 핸들러를 설정하였습니다.
- 커스텀 에러 클래스인 `RestApiException`이 발생한다는 가정 하에서 `WARN` 로그가 기록되도록 설정했습니다.
- 로그에는 커스텀 에러의 `code`와 `message`가 기록됩니다.
- 기존의 에러 발생 로그입니다.
```
Hibernate: select q1_0.id,q1_0.content,q1_0.created_at,q1_0.deleted_at,q1_0.lived_at,q1_0.popular_tags,q1_0.question_status,q1_0.updated_at from question q1_0 where (q1_0.deleted_at is null) and q1_0.question_status=? order by q1_0.id fetch first ? rows only
2024-04-21T18:00:00.109+09:00 ERROR 7 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task …
```
> [HOTFIX] 스케줄러 에러 핸들러 추가

- src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
- src/test/java/com/server/capple/domain/member/service/MemberServiceTest.java
hotfix/v0.0.2/ProfileImageNullError -> master
- 프로필 이미지 null 값에 대한 임시 처리
> [HOTFIX] 프로필 이미지 NULL값으로 인한 작성한 답변 조회 에러 수정

- src/main/java/com/server/capple/domain/answer/repository/AnswerHeartRedisRepository.java
- src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
- src/test/java/com/server/capple/domain/answer/controller/AnswerControllerTest.java
- src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java
- src/test/java/com/server/capple/domain/member/controller/MemberControllerTest.java
- src/test/java/com/server/capple/support/ControllerTestConfig.java
- close #123 
ex) test/#123/mypage -> develop
- 프로필 조회 테스트 수정
- 작성한 답변 조회 테스트 추가
- 좋아한 답변 조회 테스트 추가 
`redisTemplate.keys()`를 사용하고자 기존에 사용하던 SetOperations<>를 RedisTemplate<>으로 변경했습니다.
```java
// [AnswerHeartRedisRepository]
// @Resource(name = "redisTemplate")
//  private SetOperations<String, String> setOperations;
private final RedisTemplate<String, String> redisTemplate;
```
> [REFACTOR] 좋아한 답변 조회 수정 + 마이페이지 테스트 코드 작성

- src/main/java/com/server/capple/config/security/SecurityConfig.java
- src/main/java/com/server/capple/domain/answerComment/controller/AnswerCommentController.java
- src/main/java/com/server/capple/domain/answerComment/dto/AnswerCommentRequest.java
- src/main/java/com/server/capple/domain/answerComment/dto/AnswerCommentResponse.java
- src/main/java/com/server/capple/domain/answerComment/entity/AnswerComment.java
- src/main/java/com/server/capple/domain/answerComment/mapper/AnswerCommentMapper.java
- src/main/java/com/server/capple/domain/answerComment/repository/AnswerCommentHeartRedisRepository.java
- src/main/java/com/server/capple/domain/answerComment/repository/AnswerCommentRepository.java
- src/main/java/com/server/capple/domain/answerComment/service/AnswerCommentService.java
- src/main/java/com/server/capple/domain/answerComment/service/AnswerCommentServiceImpl.java
- src/main/java/com/server/capple/global/exception/errorCode/CommentErrorCode.java
- src/test/java/com/server/capple/domain/answerComment/controller/AnswerCommentControllerTest.java
- src/test/java/com/server/capple/domain/answerComment/service/AnswerCommentServiceTest.java
- src/test/java/com/server/capple/support/ControllerTestConfig.java
- src/test/java/com/server/capple/support/ServiceTestConfig.java
- closed #129 
ex) feat/#129/answer-comment-> develop
답변에 대한 댓글 작성, 수정, 삭제, 조회 기능을 추가했습니다.
답변에 대한 댓글 좋아요/취소 토글 기능 추가했습니다.
~작성 시간 포맷팅 로직 추가해야합니다. (기획 의도 답변 받으면 시작하겠습니다.)~ createdAt 전달
> [FEAT] 답변 댓글 CRUD, 좋아요 기능 구현

- build.gradle
- src/main/java/com/server/capple/CappleApplication.java
- src/main/java/com/server/capple/config/RedisConfig.java
- src/main/java/com/server/capple/config/apns/config/ApnsClientConfig.java
- src/main/java/com/server/capple/config/apns/dto/ApnsClientRequest.java
- src/main/java/com/server/capple/config/apns/service/ApnsService.java
- src/main/java/com/server/capple/config/apns/service/ApnsServiceImpl.java
- src/main/java/com/server/capple/config/security/jwt/service/JwtService.java
- src/main/java/com/server/capple/config/security/jwt/service/JwtServiceImpl.java
- src/main/java/com/server/capple/domain/member/controller/MemberController.java
- src/main/java/com/server/capple/domain/member/dto/MemberRequest.java
- src/main/java/com/server/capple/domain/member/repository/DeviceTokenRedisRepository.java
- src/main/java/com/server/capple/domain/member/service/MemberService.java
- src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
- src/test/java/com/server/capple/config/apns/service/ApnsServiceImplTest.java
- src/test/java/com/server/capple/domain/member/repository/DeviceTokenRedisRepositoryTest.java
Feat/#126/apns -> develop
- APNs 페이로드 발송 메서드 구현
- APNs 통신용 JWT 토큰 저장
- APNs의 토큰 베이스 인증의 JWT 토큰이 단위시간 중 계정당 한개의 값만을 사용 가능하여 퍼블릭으로 사용할 수 있는 레디스 데이터베이스를 연결
- redis cloud의 무료 데이터베이스를 이용
- `@Cacheable` 어노테이션의 사용으로 메서드 단위의 캐싱 전략을 사용
- Look Aside + Write Around 방식의 캐싱 전략을 적용 ([Look Aside, Write Around 란?](https://yoongrammer.tistory.com/101))
- APNs 의 HTTP/2 & TLS1.2 통신 정책에 따라 기존의 Http Client를 사용하지 못해 WebClient를 도입
- HTTP/2 방식의 이점을 살리기 위해 병렬처리, 논블로킹 IO, Connection Pool 을 이용하여 APNs와의 통신속도를 극대화
- 로그아웃 메서드 구현
- 기존에 로그아웃 메서드가 없었고 로그아웃 시에는 푸시알림을 받으면 안되기 때문에 디바이스 토큰 제거 로직을 추가했습니다.
병렬처리, 논블로킹 IO, Connection Pool 의 테스트 결과
- Blocking
- Non-Blocking
-> Non-Blocking으로 하나의 Connection pool을 사용할 경우 하나의 소켓주소에서 같은 주소로 너무 많은 요청이 보내져 `429 Too Many Request` Error 가 반환되어 `최소 2개 이상`의 Connection pool을 사용해야함
- 결과
- …
> [FEAT] 애플 푸시 알림 구현

- build.gradle
- src/main/java/com/server/capple/config/security/SecurityConfig.java
- src/main/java/com/server/capple/domain/board/repository/BoardHeartRedisRepository.java
- src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
- src/main/java/com/server/capple/dummy/DummyController.java
- src/main/java/com/server/capple/dummy/DummyService.java
ex) test/#140/dummyDataApi -> develop
* `i.n.r.d.DnsServerAddressStreamProviders  : Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. ` 에러가 자꾸 떠서 build.gradle에 `'io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-aarch_64'`의존성을 추가했습니다.
* 멤버 10명을 생성하고, param으로 넘겨준 수만큼 board 더미 데이터를 생성하는 API를 구현했습니다.
board 더미 데이터를 생성하는 프로시저를 사용하도록 하였습니다. (데이터베이스 내 프로시저를 만들어두었습니다.)
스웨거와 localDB로 확인하였습니다.
> [TEST] 게시판, 게시판 좋아요 더미데이터 API 생성

- src/main/java/com/server/capple/config/apns/dto/ApnsClientRequest.java
- src/main/java/com/server/capple/config/apns/service/ApnsServiceImpl.java
- src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
- src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
- src/main/java/com/server/capple/domain/boardSubscribeMember/entity/BoardSubscribeMember.java
- src/main/java/com/server/capple/domain/boardSubscribeMember/reposiotry/BoardSubscribeMemberRepository.java
- src/main/java/com/server/capple/domain/boardSubscribeMember/service/BoardSubscribeMemberService.java
- src/main/java/com/server/capple/domain/boardSubscribeMember/service/BoardSubscribeMemberServiceImpl.java
- src/main/java/com/server/capple/domain/notifiaction/entity/NotificationType.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationService.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
- src/test/java/com/server/capple/config/apns/service/ApnsServiceImplTest.java
feat/#126/apnsSetting -> develop
- 게시글에 좋아요가 눌러질 경우
- 기대하는 결과 : 게시글의 작성자에게 알림을 발송
- 페이로드 데이터 예시
```json
{
"aps" : {
"alert" : {
"title" : "누군가 내 게시글을 좋아했어요",
"body" : "{게시글 내용}"
}
"sound" : "default",
"thread-id" : "board-{boardId}"
},
"boardId" : "{boardId}"
}
```
- 게시글에 댓글이 달린 경우
- 기대하는 결과 : 게시글의 작성자와 해당 게시글의 댓글의 작성자에게 알림을 발송
- 관계형 데이터베이스에서 게시글의 댓글 알림 구독자를 저장하여 관리
```json
게시글 작성자
{
"aps" : {
"alert" : {
"title" : "누군가 내 게시글에 댓글을 달았어요",
"subtitle" : "{댓글 내용}",
"body" : "{게시글 내용}"
}
"sound" : "default",
"thread-id" : "board-{boardId}"
},
"boardId" : "{boardId}",
"boardCommentId" : "{boardCommentId}"
}
```
```json
게시글의 댓글 작성자
{
"aps" : {
"alert" : {
"title" : "누군가 내 게시글에 댓글을 달았어요",
"subtitle" : "{댓글 내용}",
"body" : "{게시글 내용}"
}
"sound" : "default",
"thread-id" : "board-{boardId}"
}, …
```
> [FEAT] 비즈니스 로직과 원격 알림 발송 로직 연결

- src/main/java/com/server/capple/config/security/SecurityConfig.java
- src/main/java/com/server/capple/domain/notifiaction/controller/NotificationController.java
- src/main/java/com/server/capple/domain/notifiaction/dto/NotificationResponse.java
- src/main/java/com/server/capple/domain/notifiaction/entity/Notification.java
- src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
- src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
- src/main/java/com/server/capple/domain/notifiaction/scheduler/NotificationScheduler.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationService.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
- src/main/java/com/server/capple/global/common/SliceResponse.java
feat/#150/saveNotifiaction -> develop
- 알림이 발생할 때 알림의 정보를 데이터베이스에도 저장
- 알림은 로그와 같은 과거의 기록이라고 여겨져 수정이 되지 않도록 연관관계 맵핑없이 컨텐트를 직접 저장했습니다.
- 댓글 작성 알림의 경우 해당 게시글에 댓글을 작성한 사용자 수 만큼 insert 쿼리가 발생하여 효율에 대해서 팔로업 하겠습니다.
- 사용자별로 알림 기록 조회 API
- 페이지네이션을 적용하였지만, 기본값을 크게두어 프론트 측의 페이지네이션 도입 전에도 큰 차이 없이 이용가능하도록 하였습니다.
- Slice를 반환하기 위한 컨벤션 객체를 작성하였습니다. 수정해야한다고 생각드신다면 얘기해주세요.
- 일주일이 지난 알림을 제거
- 스케줄러를 이용해 일주일 이상 지난 알림은 제거합니다.
> [FEAT] 알림 리스트 저장, 조회, 삭제 기능 구현

- src/main/java/com/server/capple/config/security/SecurityConfig.java
- src/main/java/com/server/capple/domain/answerComment/controller/AnswerCommentController.java
- src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
- src/main/java/com/server/capple/domain/boardComment/dto/BoardCommentResponse.java
- src/main/java/com/server/capple/domain/boardComment/entity/BoardComment.java
- src/main/java/com/server/capple/domain/boardComment/mapper/BoardCommentMapper.java
- src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
- src/main/java/com/server/capple/domain/boardCommentReport/controller/BoardCommentReportController.java
- src/main/java/com/server/capple/domain/boardCommentReport/dto/BoardCommentReportRequest.java
- src/main/java/com/server/capple/domain/boardCommentReport/dto/BoardCommentReportResponse.java
- src/main/java/com/server/capple/domain/boardCommentReport/entity/BoardCommentReport.java
- src/main/java/com/server/capple/domain/boardCommentReport/entity/BoardCommentReportType.java
- src/main/java/com/server/capple/domain/boardCommentReport/mapper/BoardCommentReportMapper.java
- src/main/java/com/server/capple/domain/boardCommentReport/repository/BoardCommentReportRepository.java
- src/main/java/com/server/capple/domain/boardCommentReport/service/BoardCommentReportService.java
- src/main/java/com/server/capple/domain/boardCommentReport/service/BoardCommentReportServiceImpl.java
- src/main/java/com/server/capple/global/exception/errorCode/BoardCommentReportErrorCode.java
- src/test/java/com/server/capple/domain/answerComment/controller/AnswerCommentControllerTest.java
- src/test/java/com/server/capple/domain/boardComment/controller/BoardCommentReportControllerTest.java
- src/test/java/com/server/capple/domain/boardComment/service/BoardCommentReportServiceTest.java
- src/test/java/com/server/capple/domain/boardCommentReport/boardComment/controller/BoardCommentControllerTest.java
- src/test/java/com/server/capple/domain/boardCommentReport/boardComment/service/BoardCommentServiceTest.java
- src/test/java/com/server/capple/support/ControllerTestConfig.java
- src/test/java/com/server/capple/support/ServiceTestConfig.java
- closed #145
ex) feat/#145/boardComment -> develop
1. 게시글 댓글 신고 기능 추가했습니다. 
2. BoardComment Entity에 isReport 추가했습니다. (신고 여부 확인용)
3. 게시글 댓글 엔드포인트 `/board-comments`로 수정했습니다.
> [FEAT] 게시판 댓글 신고함 기능 구현

- src/main/java/com/server/capple/config/security/SecurityConfig.java
- src/main/java/com/server/capple/domain/board/controller/BoardController.java
- src/main/java/com/server/capple/domain/board/dao/BoardInfoInterface.java
- src/main/java/com/server/capple/domain/board/dto/BoardRequest.java
- src/main/java/com/server/capple/domain/board/dto/BoardResponse.java
- src/main/java/com/server/capple/domain/board/entity/Board.java
- src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
- src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
- src/main/java/com/server/capple/domain/board/service/BoardService.java
- src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
- src/main/java/com/server/capple/domain/boardComment/dao/BoardCommentInfoInterface.java
- src/main/java/com/server/capple/domain/boardComment/entity/BoardComment.java
- src/main/java/com/server/capple/domain/boardComment/mapper/BoardCommentMapper.java
- src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentRepository.java
- src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
- src/main/java/com/server/capple/domain/boardReport/controller/BoardReportController.java
- src/main/java/com/server/capple/domain/boardReport/dto/BoardReportResponse.java
- src/main/java/com/server/capple/domain/boardReport/repository/BoardReportRepository.java
- src/main/java/com/server/capple/domain/boardReport/service/BoardReportService.java
- src/main/java/com/server/capple/domain/boardReport/service/BoardReportServiceImpl.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
- src/main/java/com/server/capple/domain/report/repository/ReportRepository.java
- src/main/java/com/server/capple/dummy/DummyService.java
- src/main/java/com/server/capple/dummy/generate_dummy_data.sql
- src/test/java/com/server/capple/domain/boardComment/service/BoardCommentServiceTest.java
- src/test/java/com/server/capple/domain/boardCommentReport/service/BoardCommentReportServiceTest.java
- src/test/java/com/server/capple/support/ServiceTestConfig.java
ex) refactor/#156/queryOptimization-> develop
* 게시글 조회에서 isLike 여부 확인 시 N+1문제가 발생하기 때문에, 조인과 프로젝션을 통해 게시글 조회시 isLiked, isMine을 함께 BoardInfoInterface로 받아옵니다.
* 게시글댓글 조회도 마찬가지로 수정하였습니다.
* boardComment의 member 필드명을 writer로 바꿨습니다. (권한 체크 시 혼란 방지)
* 프로시저 저장 방식을 수정하였습니다. function이 아닌 procedure로 저장하여 수행하도록 하였습니다. [function과 procedure의 차이](https://bongra.tistory.com/52)
* request dto의 content null체크는 @valid 어노테이션으로 합니다.
* 신고함 구현에 따라 isReport를 반환하도록 하였습니다. boardComment에 구현되어있는대로, board에도 isReport 필드를 만들어 저장하도록 하였습니다.
* 왜인지 모르겠다만 게시글 수정 API가 없습니다. 게시글 목록 페이징 처리할 때 함께 구현하겠습니다.
> [REFACTOR] RDB 좋아요 조회 방식 수정 

- src/main/java/com/server/capple/domain/board/controller/BoardController.java
- src/main/java/com/server/capple/domain/board/dto/BoardResponse.java
- src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
- src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
- src/main/java/com/server/capple/domain/board/service/BoardService.java
- src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
- src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
- src/main/java/com/server/capple/domain/boardComment/dto/BoardCommentResponse.java
- src/main/java/com/server/capple/domain/boardComment/mapper/BoardCommentMapper.java
- src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentRepository.java
- src/main/java/com/server/capple/domain/boardComment/service/BoardCommentService.java
- src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
- src/main/java/com/server/capple/global/common/SliceResponse.java
- src/test/java/com/server/capple/domain/boardComment/controller/BoardCommentControllerTest.java
- src/test/java/com/server/capple/domain/boardComment/service/BoardCommentServiceTest.java
- src/test/java/com/server/capple/support/ControllerTestConfig.java
- src/test/java/com/server/capple/support/ServiceTestConfig.java
ex) feature/#155/boardPagination -> develop
* 게시글, 게시글 댓글 페이징을 Slice로 구현했습니다. SliceResponse 이용하여 반환하도록 하였습니다.
* 목록 조회 조건절 설정을 다시해서 중복 조회되던 문제 해결했습니다.
게시판 테스트코드 주세요!!!!!!!!!!!
> [FEAT] 게시글, 댓글 목록 페이지네이션 구현

- src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
- src/main/java/com/server/capple/domain/answer/dao/AnswerRDBDao.java
- src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java
- src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
- src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
- src/main/java/com/server/capple/domain/answer/service/AnswerService.java
- src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
- src/main/java/com/server/capple/domain/question/controller/QuestionController.java
- src/main/java/com/server/capple/domain/question/dto/response/QuestionResponse.java
- src/main/java/com/server/capple/domain/question/mapper/QuestionMapper.java
- src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
- src/main/java/com/server/capple/domain/question/service/QuestionService.java
- src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
- src/main/java/com/server/capple/global/common/SliceResponse.java
- src/test/java/com/server/capple/domain/answer/controller/AnswerControllerTest.java
- src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java
- src/test/java/com/server/capple/domain/question/service/QuestionServiceTest.java
- src/test/java/com/server/capple/support/ControllerTestConfig.java
feat/#159/questionAnswerPagination -> develop
- pagination 공통
- Slice를 이용한 pagination을 적용하였습니다.
- 요청 값으로 `pageNumber(오프셋; 기본 0)`, `pageSize(크기; 기본 1000)`를 비필수값으로 받습니다.
- 기존의 리스트로 단건 response를 감싼 dto를 만들던 방식에서 Slice의 여러 데이터를 가진 반환 dto 템플릿을 만들어 적용했습니다.
```java
class Slice<T> {
int number; // 조회할 페이지의 위치
int size; // 조회할 페이지의 크기 (요청한 크기)
List<T> content; // 단건 조회 dto의 리스트 (변경 전의 result 반환값)
int numberOfElements; // 실제 조회된 데이터의 개수
boolean hasPrevious; // 앞선 페이지의 추가 데이터 유무
boolean hasNext; // 이후의 페이지의 추가 데이터 유무
}
```
- 프론트 측에서의 pagination 도입의 연기에 따라 page의 size를 1000으로 기본값을 설정하여 기능이 구현되기 전에도 사용이 가능하도록 하였습니다.
- 질문 조회 API
- 질문에 대한 답변 조회 API
- 질문에 대한 답변과 질문에 대한 답변 중의 키워드 검색이 함께 사용되던 것을 질문에 대한 답변 조회 단일 엔드포인트로 재구성하였습니다.
- 본인이 작성한 답변 조회 API
- 좋아요한 답변 조회 API
- 기존의 stream 내에서 repository 메서드가 사용되어 하나의 …
> [FEAT] 질문, 답변 목록 페이지네이션 구현

- src/main/resources/logback-spring.xml
ex) feat/#161/log -> develop
로그 설정을 추가해서 파일에 각각 저장하도록 했습니다.
일단 AOP 적용하지 않은 관계로
hibernate sql과 security 로그는 DEBUG로 설정하여 보여지도록 했습니다.
이런식으로, API 요청 경로가 출력되고 SQL발생 시 출력됩니닷
AOP 적용은 어떤 걸 출력하면 좋을지 더 고민해보겠습니다....
좋은 의견 환영입니다... 어떻게 하면 좋을지 이야기해주세욤
> [LOG] logback 설정

- src/main/java/com/server/capple/config/RedisConfig.java
fix/#165/disConnect-redisCloud -> develop (disconnect 는 한단어니까 disconnect 로 쓰는게 맞네요...)
- redis cloud 연결 제거
- APNs 공부를 더 해봤더니 기존에 APNs 토큰을 모든곳에서 동일한 토큰을 사용해야하는줄로 이해했던것이 HTTP 연결 하나 당 하나의 토큰을 개별적으로 가져도 되는것으로 알게되었습니다.
- `RedisConnectionFactory` 를 제거하여 redis-cloud 와의 연결을 제거하고 각 프로파일별로 APNs JWT가 개별적으로 저장되도록 변경했습니다.
- [토큰기반 으로 APNs 와 연결 구축하기](https://developer.apple.com/documentation/usernotifications/establishing-a-token-based-connection-to-apns)
- 서브모듈의 환경변수 제거는 이 PR이 머지 된 후 진행하겠습니다.
> [FIX] redis-cloud 연결 제거

- src/main/java/com/server/capple/config/apns/dto/ApnsClientRequest.java
- src/main/java/com/server/capple/config/apns/service/ApnsService.java
- src/main/java/com/server/capple/config/apns/service/ApnsServiceImpl.java
- src/main/java/com/server/capple/domain/member/repository/DeviceTokenRedisRepository.java
- src/main/java/com/server/capple/domain/notifiaction/controller/NotificationController.java
- src/main/java/com/server/capple/domain/notifiaction/dto/NotificationResponse.java
- src/main/java/com/server/capple/domain/notifiaction/entity/Notification.java
- src/main/java/com/server/capple/domain/notifiaction/entity/NotificationLog.java
- src/main/java/com/server/capple/domain/notifiaction/entity/NotificationType.java
- src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
- src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
- src/main/java/com/server/capple/domain/notifiaction/scheduler/NotificationScheduler.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationService.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
- src/main/java/com/server/capple/domain/question/scheduler/QuestionScheduler.java
- src/main/java/com/server/capple/domain/question/service/AdminQuestionService.java
- src/main/java/com/server/capple/domain/question/service/AdminQuestionServiceImpl.java
- src/test/java/com/server/capple/domain/question/service/QuestionServiceTest.java
feat/#173/questionNotification -> develop
- 질문 생성/종료 원격 알림 구현 및 알림 엔티티 구성방식 변경
- 기존의 질문 생성, 종료 상태 변경 스케줄링 메서드에서 알림 메서드를 호출하여 구현했습니다.
- 알림 엔티티의 중복 데이터를 저장하기 위해 하위 엔티티를 새로 생성하여 정규화 작업 진행했습니다.
- `CascadeType.ALL` 옵션을 이용해 연관관계 매핑을 하여 부모 엔티티인 `Notification`이 생성, 삭제가 될 때 자식엔티티인 `NotificationLog`도 함께 적용되도록 하였습니다.
- 질문 생성시 프론트에게 보내지는 객체
```json
{
"aps" : {
"alert" : {
"title" : "오늘의 질문 준비 완료!",
"body" : "{질문 내용}"
}
"sound" : "default",
"thread-id" : "question"
},
"questionId" : "{questionId}"
}
```
- 질문 종료시 프론트에게 보내지는 객체
```json
{
"aps" : {
"alert" : {
"title" : "오늘의 질문 답변 마감!",
"body" : "{질문 내용}"
}
"sound" : "default",
"thread-id" : "question"
},
"questionId" : "{questionId}"
}
```
- 질문 부제목은 잘려나와서 기획측이랑 내용을 협의해야할거 같네요
> [FEAT] 질문 생성/종료 원격 알림 구현 및 알림 엔티티 구성방식 변경

- src/main/java/com/server/capple/config/apns/service/ApnsServiceImpl.java
feat/#191/testflightApnsSetting -> develop
- 로컬의 Xcode에서 빌드한 앱은 개발용 APNs 서버를 이용하지만 테스트 플라이트 또는 앱스토어로 배포되는 앱은 실제 APNs 서버를 사용하기 떄문에 기존의 릴리즈 서버가 개발용 서버를 쓰는것이 문제가 되었습니다.
- 릴리즈 환경에서는 기본과 서브 서버를 각각 배포용, 개발용으로 지정하여 빌드 환경과 무관하게 발송되도록 하였습니다.
- APNs 로의 원격 알림 발송 실패시 작성하는 로그의 레벨을 수정하였습니다.
> [FEAT] 릴리즈 서버 연결 APNs 서버 구성 변경

- src/main/java/com/server/capple/config/RedisConfig.java
- src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
- src/main/java/com/server/capple/domain/answer/service/AnswerCountService.java
- src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
- src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
fix/#199/getAnswerFix -> develop
- 질문별 조회시 답변 총 개수 반환 값 추가
- 질문별 조회, 삭제, 생성 시 캐싱을 진행하여 반환값을 저장, 반환하도록 했습니다.
- 컨텐츠가 없을 시 반환할 lastIndex 생성 오류 수정
- `Slice`로 레포지토리 메서드 반환값을 선언하고 stream을 통해 인덱스의 최대값을 가져오는 과정에서 list가 비어있더라도 데이터를 get 해오게 되어 Exception이 발생함
- `/answers/question/{questionId}`
- 자신이 쓴 답변인지 확인하기 위해 답변별로 글쓴이를 따로 조회하여 N+1 문제가 발생함
> [FIX] 질문별 조회시 답변 총 개수 반환 값 추가 및 lastIndex 생성 오류 수정

- src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
refactor/#206/notificationN+1 -> develop
- Notification 조회 N+1 문제 해결
- `@EntityGraph` 어노테이션을 이용하여 fetch join을 구현했습니다.
기존의 쿼리
```sql
select
n1_0.id,
n1_0.created_at,
n1_0.deleted_at,
n1_0.member_id,
n1_0.notification_log_id,
n1_0.type,
n1_0.updated_at 
from
notification n1_0 
where
n1_0.id<=? 
and (
n1_0.member_id=? 
or n1_0.type=4 
or n1_0.type=5
) 
order by
n1_0.created_at desc 
offset
? rows 
fetch
first ? rows only
```
```sql
select
nl1_0.id,
nl1_0.board_comment_id,
nl1_0.board_id,
nl1_0.body,
nl1_0.created_at,
nl1_0.deleted_at,
nl1_0.question_id,
nl1_0.subtitle,
nl1_0.updated_at 
from
notification_log nl1_0 
where
nl1_0.id=?
```
수정된 쿼리
```sql
select
n1_0.id,
n1_0.created_at,
n1_0.deleted_at,
n1_0.member_id,
nl1_0.id,
nl1_0.board_comment_id,
nl1_0.board_id,
nl1_0.body, …
```
> [REFACTOR] Notification 조회 N+1 문제 해결

- src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
- src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
- src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
- src/main/java/com/server/capple/domain/board/controller/BoardController.java
- src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
- src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
- src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java
- src/main/java/com/server/capple/domain/boardComment/repository/BoardCommentRepository.java
- src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
- src/main/java/com/server/capple/domain/notifiaction/controller/NotificationController.java
- src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
- src/main/java/com/server/capple/domain/question/controller/QuestionController.java
- src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
- src/main/java/com/server/capple/domain/question/service/QuestionService.java
- src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
- src/main/java/com/server/capple/global/common/SliceResponse.java
- src/test/java/com/server/capple/domain/boardComment/controller/BoardCommentControllerTest.java
- src/test/java/com/server/capple/domain/boardComment/service/BoardCommentServiceTest.java
- src/test/java/com/server/capple/support/ControllerTestConfig.java
fix/#208/noOffsetPagination -> develop
- 페이지네이션 방식을 노오프셋 페이징 기법으로 변경하였습니다. [No Offeset 이란](https://liltdevs.tistory.com/196)
- 기존의 방법의 컨텐츠 제한선을 둔 컨텐츠 고정 방식은 잘 쓰지 않는 방법이라 판단하였으며, 마지막으로 조회한 데이터의 마지막 인덱스를 이용한 페이지네이션 방식인 노오프셋 방식이 무한스크롤에서 더 적합하다고 판단하여 수정하게 되었습니다.
- 페이지네이션을 사용하는 API의 요청,반환값의 수정이 있습니다.
- 요청값
- `pageNumber` 제거 : 노오프셋 방식은 이전의 인덱스를 기준으로 다음 컨텐츠를 조회하는 방식으로 현재 페이지 위치가 필요하지 않게 되었습니다.
- 반환값
- `hasPrevious` 제거 : 노오프셋 방식과 무한 스크롤 방식의 특징상 앞선 데이터가 있는지는 중요하지 않아 제거하였습니다.
- `number` 제거 : 요청값의 설명과 동일합니다.
- JPQL로 사용해도 되지만 Pageable을 이용하는 이유
- JPA의 Slice를 사용하기 위해서는 Pageable 객체를 argument로 주어져야 한다는 조건이 있는것으로 파악하였습니다.
- `Slice`를 써야하는 이유로는 다음의 컨텐츠가 존재하는지(`hasNext`), 실제로 불러와진 데이터가 몇개인지(`numberOfElements`)을 자바 코드로 작성하지 않고 반환받을 수 있다는점입니다.
- 수정된 페이지네이션 플로우는 다음과 같습니다.
```mermaid
sequenceDiagram
actor u as …
```
> [FIX] 노오프셋 페이징 기법으로 변경

- src/main/java/com/server/capple/domain/answer/dao/AnswerRDBDao.java
- src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
- src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java
- src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
refactor/#210/getAnswerN+1 -> develop
- 답변 조회 시 문제 글쓴이의 id, 프로필 이미지, 닉네임이 Member 엔티티와의 LAZY fetch 전략으로 인해 N+1 문제가 발생했습니다.
- `Projection`을 이용하여 한쿼리로 반환에 필요한 데이터만 join후 불러오도록 구현했습니다.
변경 전 쿼리
```sql
select
a1_0.id,
a1_0.content,
a1_0.created_at,
a1_0.deleted_at,
a1_0.member_id,
a1_0.question_id,
a1_0.updated_at,
(r1_0.id is not null) 
from
answer a1_0 
left join
report r1_0 
on r1_0.answer_id=a1_0.id 
where
(
a1_0.deleted_at is null
) 
and a1_0.id<=? 
and a1_0.question_id=? 
order by
a1_0.created_at desc 
offset
? rows 
fetch
first ? rows only
```
LAZY 전략으로 인한 N개의 추가 쿼리
```sql
select
m1_0.member_id,
m1_0.created_at,
m1_0.deleted_at,
m1_0.email,
m1_0.nickname,
m1_0.profile_image,
m1_0.role,
m1_0.sub,
m1_0.updated_at 
from
member m1_0 
where
m1_0.member_id=?
```
변경 후 쿼리
```sql
select
a1_0.id, …
```
> [REFACTOR] 답변 조회 N+1 문제 해결

- src/main/java/com/server/capple/domain/board/dao/BoardInfoInterface.java
- src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
- src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
- src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java
refactor/#212/getBoardN+1 -> develop
- 게시글 조회 시 게시글의 글쓴이의 닉네임이 Member 엔티티와의 LAZY fetch 전략으로 인해 N+1 문제가 발생했습니다.
- Projection을 이용하여 한 쿼리로 반환에 필요한 데이터만 join후 불러오도록 구현했습니다.
```sql
select
distinct b1_0.id,
b1_0.board_type,
b1_0.comment_count,
b1_0.content,
b1_0.created_at,
b1_0.deleted_at,
b1_0.heart_count,
b1_0.is_report,
b1_0.updated_at,
b1_0.member_id,
case 
when bh1_0.is_liked=true 
then true 
else false 
end,
case 
when b1_0.member_id=? 
then true 
else false 
end 
from
board b1_0 
left join
board_heart bh1_0 
on b1_0.id=bh1_0.board_id 
and bh1_0.member_id=? 
where
(
b1_0.deleted_at is null
) 
and (
? is null 
or b1_0.board_type=?
) 
and b1_0.id<=? 
order by
b1_0.created_at desc 
offset
? rows 
fetch
first ? rows only
```
LAZY fetch 전략으로 인해 추가적으로 발생하는 N개의 쿼리
```sql
select
m1_0.member_id, …
```
> [REFACTOR] 게시글 조회 N+1문제 해결

- src/main/java/com/server/capple/domain/notifiaction/entity/Notification.java
- src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
- src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
fix/#223/removeBeforeRegisterNoti -> develop
- 알림 회원 연관관계 설정
- 식별번로로만 처리하던 알림을 수신한 회원의 정보를 연관관계를 추가해줬습니다.
- 가입 전 알림 조회 차단
- 가입 전에 발생한 공통알림(오늘의 질문 시작/종료)이 보이던 오류를 서브쿼리를 이용해 생성일 기준으로 처리했습니다.
> [FIX] 알림 회원 연관관계 설정 및 가입 전 알림 조회 차단

- src/main/java/com/server/capple/config/apns/dto/ApnsClientRequest.java
hotfix/#229/remoteNotiSoundless -> master
질문과 댓글 원격 알림이 알림 사운드가 발생하지 않던 버그를 수정했습니다.
- 기존의 컨트롤러를 통한 원격 알림 테스트시 사용하던 `@Schema(defaultValue = "default")` 를 통해 알림 사운드의 기본값을 지정하던 방식으로 인해 실제 서비스 구현에서 사용하는 `Builder` 패턴 방식의 기본값 설정법이 맞지 않아 사운드 값이 null로 전달되었습니다.
- `@Builder.Default` 를 이용해 기본 알림사운드를 설정하는 방식으로 완료했습니다.
> [HOTFIX] 질문, 댓글 원격 알림의 알림 사운드 설정

- src/main/java/com/server/capple/domain/question/scheduler/QuestionScheduler.java
feat/#235/questionPeriodChange -> develop
- 질문 횟수 변경 (2회 -> 1회)
- 질문 시간 변경 (open) 12:30 / (close) 23:59:59
```java
@Scheduled(cron = "0 30 12 * * *") //매일 오후 12시 30분에
public void setLiveQuestion() {
Question question = adminQuestionService.setLiveQuestion();
notificationService.sendLiveQuestionOpenNotification(question);
log.info("live question이 등록되었습니다.");
}
@Scheduled(cron = "59 59 23 * * *") //매일 오후 23시 59분 59초에
public void closeLiveQuestion() {
//question을 닫음
Question question = adminQuestionService.closeLiveQuestion();
notificationService.sendLiveQuestionCloseNotification(question);
log.info("live question이 닫혔습니다.");
}
```
> 라이브 질문 시간 수정 및 횟수 변경

- src/main/java/com/server/capple/config/security/jwt/service/JwtService.java
- src/main/java/com/server/capple/config/security/jwt/service/JwtServiceImpl.java
- src/main/java/com/server/capple/domain/member/entity/Member.java
- src/main/java/com/server/capple/domain/member/repository/MemberRepository.java
- src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
- src/test/java/com/server/capple/domain/member/repository/MemberRepositoryTest.java
- src/test/java/com/server/capple/domain/member/service/MemberServiceTest.java
feat/245/signupWithDuplicateEmail -> develop
- 이메일 발송 시 중복 메일의 존재를 검증하는 과정을 제거했습니다.
- 회원 가입 시 동일한 이메일을 가진 회원이 이미 존재하는 경우 기존의 회원의 정보에 sub만 덮어쓰도록 변경했습니다.
> [FEAT] 중복 이메일 가입 시 통합되도록 수정

- src/main/java/com/server/capple/config/apns/dto/ApnsClientRequest.java
- src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
- src/main/java/com/server/capple/domain/answerComment/dto/AnswerCommentDBResponse.java
- src/main/java/com/server/capple/domain/answerComment/repository/AnswerCommentRepository.java
- src/main/java/com/server/capple/domain/answerComment/service/AnswerCommentServiceImpl.java
- src/main/java/com/server/capple/domain/answerSubscribeMember/entity/AnswerSubscribeMember.java
- src/main/java/com/server/capple/domain/answerSubscribeMember/repository/AnswerSubscribeMemberRepository.java
- src/main/java/com/server/capple/domain/answerSubscribeMember/service/AnswerSubscribeMemberService.java
- src/main/java/com/server/capple/domain/answerSubscribeMember/service/AnswerSubscribeMemberServiceImpl.java
- src/main/java/com/server/capple/domain/notifiaction/dto/NotificationDBResponse.java
- src/main/java/com/server/capple/domain/notifiaction/dto/NotificationResponse.java
- src/main/java/com/server/capple/domain/notifiaction/entity/NotificationLog.java
- src/main/java/com/server/capple/domain/notifiaction/entity/NotificationType.java
- src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
- src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationService.java
- src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
- src/test/java/com/server/capple/domain/answerComment/service/AnswerCommentServiceTest.java
- src/test/java/com/server/capple/domain/answerSubscribeMember/repository/AnswerSubscribeMemberRepositoryTest.java
- src/test/java/com/server/capple/domain/answerSubscribeMember/service/AnswerSubscribeMemberServiceImplTest.java
- src/test/java/com/server/capple/domain/notifiaction/repository/NotificationRepositoryTest.java
- src/test/java/com/server/capple/domain/notifiaction/service/NotificationServiceImplTest.java
feat/#252/answerNotification -> develop
- 답변의 새로운 댓글 알림 발송
- event : 답변의 새로운 댓글 작성
- subscriber : 해당 답변의 작성자, 해당 답변에 댓글을 이미 남긴 사람
- apns 알림 그룹을 `answer-{answerId}`로 설정하여 답변 별로 알림그룹이 형성되도록 했습니다.
- 앱 내 notification 조회 시 `questionId`, `answerId`, `answerCommentId`, `isResponsedQuestion` 을 함께 보내줍니다.
- APNs 알림 객체에 `answerId`(답변 id)와 `answerCommentId`(답변의 댓글 id) 를 함께 보냅니다.
- 답변의 좋아요 알림 발송
- event : 답변의 좋아요 누르기
- subscriber : 답변의 작성자
- apns 알림 그룹을 `answer-{answerId}`로 설정하여 답변 별로 알림그룹이 형성되도록 했습니다.
- 앱 내 notification 조회 시 `questionId`, `answerId`, `isResponsedQuestion` 을 함께 보내줍니다.
- APNs 알림 객체에 `answerId` 를 함께 보냅니다.
- 답변의 댓글 좋아요 알림 발송
- event : 답변의 댓글 좋아요 누르기
- subscriber : 답변의 댓글 작성자
- apns 알림 그룹을 `answer-{answerId}`로 설정하여 답변 별로 알림그룹이 형성되도록 했습니다.
- 앱 내 notification 조회 시 `questionId`, `answerId`, …
> [FEAT] 답변 좋아요 알림, 답변 댓글 알림, 답변 댓글 좋아요 알림 구현

- src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
- src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java
fix/#271/answerLikeError -> develop
- ANSWER isLiked 필드 AnswerHeart 없을 시 null로 반환되던 에러 수정 (null이면 false로 반환하게끔 수정)
> [FIX] ANSWER - isLiked 좋아요 관련 에러 수정
