Team-Capple/Capple-Server

.gitignore, build.gradle, src/main/java/com/server/capple/CappleApplication.java, src/main/java/com/server/capple/config/RedisConfig.java, src/main/java/com/server/capple/domain/answer/entity/Answer.java, src/main/java/com/server/capple/domain/answer/entity/AnswerHeart.java, src/main/java/com/server/capple/domain/member/entity/Member.java, src/main/java/com/server/capple/domain/proposal/entity/Proposal.java, src/main/java/com/server/capple/domain/question/entity/Question.java, src/main/java/com/server/capple/domain/question/entity/QuestionHeart.java, src/main/java/com/server/capple/domain/tag/Tag.java, src/main/java/com/server/capple/global/common/BaseEntity.java, src/test/java/com/server/capple/CappleApplicationTests.java
Closes #2 
1. 엔티티 매핑
2. 레디스 의존성 추가, config 파일 작성
태그 엔티티는 따로 생성하지는 않고 일단 DTO만 만들어두었습니당..
=> [FEAT] 엔티티 세팅

build.gradle, src/main/java/com/server/capple/CappleApplication.java, src/main/java/com/server/capple/config/SwaggerConfig.java
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[x] 의존성, 환경 변수, 빌드 관련 코드 업데이트
feature/#7/swagger -> develop
- #7 
spring doc 이용해서 swagger 설정했습니다. 
시큐리티 설정되면 테스트 내용 첨부하도록 하겠습니다.
=> [CHORE] Swagger 세팅

build.gradle, src/main/java/com/server/capple/config/S3Config.java, src/main/java/com/server/capple/global/utils/S3ImageComponent.java
- #12 
feature/#12/s3-image-util -> develop
AWS S3 이미지 업로드 유틸 파일 생성했습니다. 
AWS S3에서 업로드, 삭제 테스트 결과 확인했습니다!
=> [FEAT] S3 이미지 업로드 및 삭제 유틸 생성

src/main/java/com/server/capple/CappleApplication.java, src/main/java/com/server/capple/domain/tag/repository/TagRedisRepository.java, src/main/java/com/server/capple/domain/tag/scheduler/TagScheduler.java
ex) feature/#27/tag-scheduler -> develop
-@scheduled cron 사용하여 매일 밤 12시 tag count 50% 감소
로그로 확인하였습니다~!
=> [FEAT] tag 스케줄러 설정

src/main/java/com/server/capple/config/SwaggerConfig.java
feature/#35/SwaggerJwtSetting -> develop
- JWT 전역 설정
=> [FEAT] Swagger Jwt설정

src/main/java/com/server/capple/domain/answer/controller/AnswerController.java, src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java, src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java, src/main/java/com/server/capple/domain/answer/repository/AnswerHeartRedisRepository.java, src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java, src/main/java/com/server/capple/domain/answer/service/AnswerService.java, src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
- #24 
feature/#24/mypage-contents -> develop
1. 작성한 답변 조회 API 추가
2. 좋아한 댓글 조회 API 추가
=> [FEAT] 작성한 답변 조회/좋아한 댓글 조회 기능 추가

src/main/java/com/server/capple/domain/answer/repository/AnswerRepository.java, src/main/java/com/server/capple/domain/question/controller/QuestionController.java, src/main/java/com/server/capple/domain/question/dto/response/QuestionResponse.java, src/main/java/com/server/capple/domain/question/mapper/QuestionMapper.java, src/main/java/com/server/capple/domain/question/service/QuestionService.java, src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java
feature/#37/FixQuestions -> develop
- 질문 모아보기 DTO에 멤버가 해당 질문에 대한 답변을 했는지에 대한 여부(isAnswered) 추가
=> [FEAT] MVP 축소에 따른 수정 및 기능 추가

src/main/java/com/server/capple/domain/answer/controller/AnswerController.java, src/main/java/com/server/capple/domain/answer/service/AnswerService.java, src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java, src/main/java/com/server/capple/domain/member/controller/MemberController.java, src/main/java/com/server/capple/domain/member/service/MemberService.java, src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java, src/test/java/com/server/capple/domain/member/controller/MemberControllerTest.java, src/test/java/com/server/capple/domain/member/service/MemberServiceTest.java
- Closed #41 
refactor/#41/login-annotation -> develop
작업한 api에 로그인 어노테이션을 적용했습니다 .
=> [REFACTOR] 로그인 어노테이션 적용

src/main/java/com/server/capple/domain/question/dto/response/QuestionResponse.java
fix/#39/QuestionSummary -> develop
Question DTO boolean -> Boolean 자료형 수정
=> [FIX] Question DTO boolean -> Boolean 자료형 수정

src/main/java/com/server/capple/domain/member/controller/MemberController.java, src/main/java/com/server/capple/domain/member/dto/MemberRequest.java, src/main/java/com/server/capple/domain/member/dto/MemberResponse.java, src/main/java/com/server/capple/domain/member/entity/Member.java, src/main/java/com/server/capple/domain/member/mapper/MemberMapper.java, src/main/java/com/server/capple/domain/member/service/MemberService.java, src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java, src/test/java/com/server/capple/domain/member/controller/MemberControllerTest.java, src/test/java/com/server/capple/domain/member/service/MemberServiceTest.java, src/test/java/com/server/capple/support/ControllerTestConfig.java, src/test/java/com/server/capple/support/ServiceTestConfig.java
feature/#48/DeleteEmailField -> develop
- 불필요한 email 필드를 제거했습니다.
=> [FIX] Member 엔티티에서 불필요한 Field 삭제(email)

src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java
fix/#53/EditProfile -> develop
- 마이페이지 프로필 수정 오류 해결
=> [FIX] 프로필 업데이트 오류 수정

src/main/java/com/server/capple/domain/member/controller/MemberController.java, src/main/java/com/server/capple/domain/member/dto/MemberRequest.java, src/main/java/com/server/capple/domain/member/entity/Member.java, src/main/java/com/server/capple/domain/member/mapper/MemberMapper.java, src/main/java/com/server/capple/domain/member/service/MemberService.java, src/main/java/com/server/capple/domain/member/service/MemberServiceImpl.java, src/test/java/com/server/capple/support/ControllerTestConfig.java
fix/#56/AddEmailField-> develop
- Member 엔티티에 email 필드 추가
=> [FIX] Member 엔티티에 email 필드 추가

src/main/java/com/server/capple/CappleApplication.java
feature/#62/change-timezone -> develop
- 시간대를 서울로 변경
=> [FEAT] 시간대를 서울로 변경

src/main/java/com/server/capple/domain/question/dto/response/QuestionResponse.java
fix/#64/FormattingDate -> develop
- 질문 모 아보기 API LivedAt 형식 설정("yyyy-MM-dd'T'HH:mm:ss")
=> [FIX] 날짜 반환 형식 변경

src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java
fix/#66/ChangeSortMethodGetQuestionList -> develop
- 질문 모아보기 정렬 형식 오름차순으로 변경
=> [FIX] 질문 모아보기 정렬 방식 변경

src/main/java/com/server/capple/config/security/SecurityConfig.java
hotfix/#69/fix-endpoint-check -> develop
- 이메일, 닉네임 체크 엔드포인트의 접근 권한에 대한 수정
=> [HOTFIX] 이메일, 닉네임 체크 엔드포인트 필터링 제거

src/main/java/com/server/capple/domain/member/entity/Member.java
fix/#75/ResignMember -> develop
회원 탈퇴 시 (email, sub) 필드 삭제 추가
=> [FIX] 회원 탈퇴 API 수정

src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java
fix/#85/memberAnswerListResoinse-fix -> develop
- MemberAnswerList 응답 객체 Getter 어노테이션 추가
=> [FIX] MemberAnswerList 응답 객체 Getter 어노테이션 추가

src/main/java/com/server/capple/domain/answer/controller/AnswerController.java, src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java, src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java, src/main/java/com/server/capple/domain/answer/service/AnswerService.java, src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java
feature/#87/isMyAnswer -> develop
- 답변 조회 시 본인 답변 여부 데이터 추가
=> [FEAT] 답변 조회 시 본인 답변 여부 데이터 추가

src/main/java/com/server/capple/config/security/SecurityConfig.java, src/main/java/com/server/capple/domain/report/controller/ReportController.java, src/main/java/com/server/capple/domain/report/dto/reponse/ReportResponse.java, src/main/java/com/server/capple/domain/report/dto/request/ReportRequest.java, src/main/java/com/server/capple/domain/report/entity/Report.java, src/main/java/com/server/capple/domain/report/entity/ReportType.java, src/main/java/com/server/capple/domain/report/mapper/ReportMapper.java, src/main/java/com/server/capple/domain/report/repository/ReportRepository.java, src/main/java/com/server/capple/domain/report/service/ReportService.java, src/main/java/com/server/capple/domain/report/service/ReportServiceImpl.java, src/main/java/com/server/capple/global/exception/errorCode/ReportErrorCode.java
feature/#74/ReportAPI -> develop
=> [FEAT] 신고함 API 구현

src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java, src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java, src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java, src/main/java/com/server/capple/domain/report/repository/ReportRepository.java, src/main/java/com/server/capple/domain/report/service/ReportService.java, src/main/java/com/server/capple/domain/report/service/ReportServiceImpl.java
feature/#94/ReportedAnswer -> develop
- 답변에 대한 신고 여부 확인 기능 구현
=> [FEAT] 답변 조회시 신고당한 답변 필터링

src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java, src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java
fix/#96/ReturnEntityId -> develop
- 질문/답변 조회 시 id값 반환 코드 추가
=> [FIX] 질문/답변 조회 시 id값 반환 코드 추가

src/main/java/com/server/capple/domain/tag/repository/TagRedisRepository.java
ex) feature/#43/popular-keyword
태그 score가 1보다 낮아져도 삭제하지 않도록 수정했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
=> [FIX] 태그 score가 1보다 낮아져도 삭제하지 않도록 수정

.github/workflows/ci.yml, .github/workflows/cicd-production.yml, .github/workflows/cicd-release.yml, Dockerfile-deploy
release-0.0.1 -> develop
- 운영서버, 릴리즈 서버의 배포 파이프라인의 수정
- 운영서버
- 릴리즈 서버
=> [RELEASE] 0.0.1 버전 수정사항

build.gradle, src/main/java/com/server/capple/domain/tag/dto/TagResponse.java, src/main/java/com/server/capple/domain/tag/mapper/TagMapper.java, src/test/java/com/server/capple/domain/tag/controller/TagControllerTest.java
- [] 기능 추가
ex) fix/#107/buildWarningReslove -> develop
빌드 워닝 해결
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
=> [FIX] 빌드 워닝 해결

src/main/java/com/server/capple/domain/question/repository/QuestionRepository.java, src/test/java/com/server/capple/domain/question/service/QuestionServiceTest.java
hotfix/v0.0.1/HotfixIsAnswered -> master
질문 삭제 시 isAnswered가 갱신 안되는 버그 수정
=> [HOTFIX] 답변 삭제 후 isAnswered 업데이트

src/main/java/com/server/capple/domain/answer/controller/AnswerController.java
hotfix/v0.0.2/DeletePagingGetAnswers -> develop
- 프론트 미구현으로 인한 페이징 상수 처리 임시 코드 추가
=> [HOTFIX] 답변 페이징 해제

.github/workflows/cicd-production.yml, src/main/java/com/server/capple/config/SwaggerConfig.java
style/#109/serverVersion -> develop
- 운영 프로파일 스웨거 깃헙 링크 추가 및 버전정보 표현
- 운영용 스웨거에서는 버전정보가 표현되며, 버전의 변경사항을 볼 수 있는 url 도 추가하였습니다.
=> [STYLE] 운영 프로파일 스웨거 깃헙 링크 추가 및 버전정보 표현

src/main/java/com/server/capple/domain/answer/dto/AnswerRequest.java, src/main/java/com/server/capple/domain/answer/dto/AnswerResponse.java, src/main/java/com/server/capple/domain/answer/entity/Answer.java, src/main/java/com/server/capple/domain/answer/mapper/AnswerMapper.java, src/main/java/com/server/capple/domain/answer/service/AnswerService.java, src/main/java/com/server/capple/domain/answer/service/AnswerServiceImpl.java, src/main/java/com/server/capple/domain/question/dao/QuestionInfoInterface.java, src/main/java/com/server/capple/domain/question/dto/response/QuestionResponse.java, src/main/java/com/server/capple/domain/question/entity/Question.java, src/main/java/com/server/capple/domain/question/mapper/QuestionMapper.java, src/main/java/com/server/capple/domain/question/scheduler/QuestionScheduler.java, src/main/java/com/server/capple/domain/question/service/AdminQuestionService.java, src/main/java/com/server/capple/domain/question/service/AdminQuestionServiceImpl.java, src/main/java/com/server/capple/domain/question/service/QuestionServiceImpl.java, src/main/java/com/server/capple/domain/tag/scheduler/TagScheduler.java, src/test/java/com/server/capple/domain/answer/controller/AnswerControllerTest.java, src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java, src/test/java/com/server/capple/domain/question/service/QuestionServiceTest.java, src/test/java/com/server/capple/domain/tag/controller/TagControllerTest.java, src/test/java/com/server/capple/domain/tag/service/TagServiceTest.java, src/test/java/com/server/capple/support/ControllerTestConfig.java, src/test/java/com/server/capple/support/ServiceTestConfig.java
ex) feature/#125/deprecateTag -> develop
* question, answer 도메인에서 tag 기능을 제거하였습니다. 
* tag 기능 제거에 따라 테스트코드를 업데이트 하였습니다.
* Tag 도메인은 따로 삭제하지 않았습니다~~
=> [FEAT] TAG 기능 삭제 

src/test/java/com/server/capple/domain/answer/controller/AnswerControllerTest.java, src/test/java/com/server/capple/domain/answer/service/AnswerServiceTest.java, src/test/java/com/server/capple/support/ControllerTestConfig.java
ex) feature/#126/deprecateTag-> develop
앞전 pr에 태그 관련 코드가 있었나봐욤 테스트 통과가 안돼서 수정해서 다시 pr 올립니다 ㅎㅎ
=> [FEAT] TAG 기능 삭제에 따른 test code 수정

src/main/java/com/server/capple/config/security/SecurityConfig.java, src/main/java/com/server/capple/domain/board/controller/BoardController.java, src/main/java/com/server/capple/domain/board/dto/BoardRequest.java, src/main/java/com/server/capple/domain/board/dto/BoardResponse.java, src/main/java/com/server/capple/domain/board/entity/Board.java, src/main/java/com/server/capple/domain/board/entity/BoardType.java, src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java, src/main/java/com/server/capple/domain/board/repository/BoardHeartRedisRepository.java, src/main/java/com/server/capple/domain/board/repository/BoardRepository.java, src/main/java/com/server/capple/domain/board/service/BoardService.java, src/main/java/com/server/capple/domain/board/service/BoardServiceImpl.java, src/main/java/com/server/capple/global/exception/errorCode/BoardErrorCode.java
feat/#128/boardAPI -> develop
- 게시글 작성 API 구현
- 카테고리별 게시글 조회 API 구현
- 게시글 삭제 API 구현
- 게시글 검색 API 구현
- 게시글 좋아요 토글 API 구현
일정 관계상... 테스트코드는 추후에 짜도록 하겠습니다. (예외처리 잘 해놨어요 ㅠㅠ...)
=> [FEAT] 게시판 기능 구현

src/main/java/com/server/capple/config/security/SecurityConfig.java, src/main/java/com/server/capple/domain/boardReport/controller/BoardReportController.java, src/main/java/com/server/capple/domain/boardReport/dto/BoardReportRequest.java, src/main/java/com/server/capple/domain/boardReport/dto/BoardReportResponse.java, src/main/java/com/server/capple/domain/boardReport/entity/BoardReport.java, src/main/java/com/server/capple/domain/boardReport/entity/BoardReportType.java, src/main/java/com/server/capple/domain/boardReport/mapper/BoardReportMapper.java, src/main/java/com/server/capple/domain/boardReport/repository/BoardReportRepository.java, src/main/java/com/server/capple/domain/boardReport/service/BoardReportService.java, src/main/java/com/server/capple/domain/boardReport/service/BoardReportServiceImpl.java, src/main/java/com/server/capple/domain/report/repository/ReportRepository.java, src/main/java/com/server/capple/global/exception/errorCode/BoardReportErrorCode.java
feat/#142/boardReport -> develop
- 게시판 신고 API
- 게시판 신고 수정 API
- 본인이 신고한 게시판 조회 API
- 게시판 신고 삭제 API
=> [FEAT] 신고함 기능 구현(게시판)

build.gradle, src/main/java/com/server/capple/config/security/SecurityConfig.java
feat/#157/advancedSpringMonitor -> develop
- 메트릭 모니터링을 위한 엔드포인트를 개방했습니다.
- 저도 사용법은 익히고 있는상태라 자세한 설명은 생략하겠습니다..
- [스프링 부트 액추에이터 사용하기](https://incheol-jung.gitbook.io/docs/study/srping-in-action-5th/chap-16.)
- 다른 프로젝트에서도 사용중인데 다음 사진과 깉이 서버의 엔드포인트별 레이턴시도 측정할 수 있습니다.
=> [FEAT] 스프링 메트릭 모니터링  설정

docker-compose.prod.yml, docker-compose.release.yml
deploy/#167/springLogFileMount -> develop
- 배포 시에 스프링 컨테이너에서 로그가 저장되는 `/app/logs` 디렉토리가 서버의 로그 저장 디렉토리와 마운트 되도록 설정했습니다.
=> [DEPLOY] 로그 수집을 위한 스프링 컨테이너 볼륨 마운트 설정

src/main/java/com/server/capple/config/apns/dto/ApnsClientRequest.java, src/main/java/com/server/capple/domain/notifiaction/entity/NotificationType.java, src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java
feat/#178/notificationContent -> develop
- 원격 알림 양식 변경
- 기획측 요구사항
=> feat: #178 원격 알림 양식 변경

src/main/java/com/server/capple/domain/boardComment/controller/BoardCommentController.java, src/main/java/com/server/capple/domain/boardComment/service/BoardCommentServiceImpl.java
ex) fix/#197/commentOrder -> develop
댓글 목록의 경우 오름차순 정렬되도록 수정하였습니다.
=> [FIX] 게시글 댓글 정렬 기준 수정

src/main/java/com/server/capple/domain/mail/service/MailUtilImpl.java
fix/#217/whitelistMailNoSend -> develop
화이트리스트에 있을 시 메일 발송을 하지 않도록 수정
=> [FIX] 화이트리스트에 있을 시 메일 발송을 하지 않도록 수정

src/main/java/com/server/capple/domain/mail/service/MailUtilImpl.java
fix/#219/cerMailTitleChange -> develop
인증메일 제목 변경
=> [FIX] 인증메일 제목 변경

src/main/java/com/server/capple/domain/mail/service/MailUtilImpl.java, src/main/java/com/server/capple/domain/notifiaction/entity/Notification.java, src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java, src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java, src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
develop -> release-v0.1.0
[FIX] 알림 회원 연관관계 설정 및 가입 전 알림 조회 차단 #224
=> [RELEASE] 알림 회원 연관관계 설정 및 가입 전 알림 조회 차단

src/main/java/com/server/capple/domain/notifiaction/dto/NotificationDBResponse.java, src/main/java/com/server/capple/domain/notifiaction/dto/NotificationResponse.java, src/main/java/com/server/capple/domain/notifiaction/entity/NotificationLog.java, src/main/java/com/server/capple/domain/notifiaction/mapper/NotificationMapper.java, src/main/java/com/server/capple/domain/notifiaction/repository/NotificationRepository.java, src/main/java/com/server/capple/domain/notifiaction/service/NotificationServiceImpl.java
feat/#233/notificationInteractionInfoAdd -> develop
- 알림 조회시 게시글 신고 여부
- `notification_log` 테이블과 `board_report` 테이블을 `board_id` 으로 left join 하여 신고가 접수된 게시글인지 확인했습니다.
- 기존의 dto에 `isReportedBoard` 필드를 추가해줬습니다.
- 기존의 엔티티 `Notification` 전체를 쿼리 하던 SQL을 projection을 통해 엔티티와 함께 `isReportedBoard` 를 받아올 수 있도록 interface 를 이용해 변경했습니다.
- 질문 답변 여부 반환
- `notification_log` 테이블과 `answer` 테이블을 `question_id` 으로 left join 하여 답변한 질문인지 확인했습니다.
- 기존의 dto에 `isResponsedQuestion` 필드를 추가해줬습니다.
- 기존의 엔티티 `Notification` 전체를 쿼리 하던 SQL을 projection을 통해 엔티티와 함께 `isResponsedQuestion` 를 받아올 수 있도록 interface 를 이용해 변경했습니다.
- 알림 로그 테이블 연관관계 컨텐츠와 연결
- notification_log` 테이블과 연관관계가 정의 되어 있지 않던 `question`, `board`, `board_comment` 테이블에 연관관계를 생성해주었습니다.
- 아래와 같은 조건으로 테스트한 결과 예시 json과 같은 dto로 잘 반환됨을 확인했습니다.
- `게시글1`, `게시글2` 를 작성하고 …
=> 알림 리스트 상호작용을 위한 API dto 데이터 추가

src/main/java/com/server/capple/config/security/jwt/service/JwtServiceImpl.java
chore/#259/separateTeamId -> develop
- 로그인, APNs 팀 id 분리
=> [CHORE] 로그인, APNs 팀 id 분리
